service: serverless-appsync-template

plugins:
  - serverless-webpack
  - serverless-appsync-plugin 
  - serverless-appsync-simulator
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'ap-northeast-1'}

package:
  patterns:
    - '!node_modules/aws-sdk/**'

functions: ${file(./config/functions.yml)}

custom:
  webpack:
    includeModules: true
    packager: 'npm'
  appsync-simulator:
    location: ".webpack/service"
    watch: false
  appSync: ${file(./config/appsync.yml)}

resources: ${file(./config/resources.yml)}